# Generated by Django 4.0.3 on 2022-05-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=50)),
                ('UserPassword', models.CharField(max_length=50)),
                ('IsAdmin', models.CharField(max_length=10)),
            ],
        ),
    ]
